name: Build
on: [push, pull_request]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: gradle/actions/wrapper-validation@d156388eb19639ec20ade50009f3d199ce1e2808
  gradle:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        java-version: 11
        distribution: zulu
    - uses: eskatos/gradle-command-action@ac2d340dc04d9e1113182899e983b5400c17cda1
      with:
        arguments: build --parallel --continue
